language: node_js

node_js:
  - "6"

services:
  - postgresql

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/courtbook"
    - DATABASE_DIALECT="postgres"

before_script:
  - psql -c 'create database courtbook;' -U postgres
  - node_modules/.bin/sequelize db:migrate
